public enum PlayerFieldPositionEnum
{
    BATTER,
    PITCHER,
    RUNNER,
    CATCHER,
    FIRST_BASEMAN,
    SECOND_BASEMAN,
    THIRD_BASEMAN,
    SHORT_STOP,
    LEFT_FIELDER,
    CENTER_FIELDER,
    RIGHT_FIELDER
}
